### ISSUE TITLE
执行yao run scripts.doc.SchemaReset 报错

### ISSUE THREAD

**Issue by zhubingbing** [YaoApp/yao-knowledge#1]
基于master分支

(base) [root@dev-vm yao-knowledge]# yao migrate --reset --force  && yao run scripts.doc.SchemaReset
Update schema model: admin.user (admin_user)    SUCCESS
Update schema model: user (user)        SUCCESS
Run: scripts.doc.SchemaReset
{}
Process: doc.SchemaReset TypeError: Cannot read properties of null (reading 'error')

**Comment by trheyi** [comment]
1. 确认你 .env 里的 YAO_ROOT 路径
2. Clone 代码，在应用源码目录运行命令
