### ISSUE TITLE
mac上运行knowledge-desktop，服务器返回错误

### ISSUE THREAD

**Issue by helperAI** [YaoApp/yao-knowledge#2]
mac上运行如下：
npm start

> yao-knowledge-desktop@1.0.0 start
> electron .

右上角出现小黑色方框，拖入pdf文件后，报如下错误：
![image](https://github.com/YaoApp/yao-knowledge/assets/75373309/ebc61c9b-0dbb-4c33-9257-26b5c0f41181)

进一步检查yao服务端的application.log文件后面500行如下：
[application.log.txt](https://github.com/YaoApp/yao-knowledge/files/11678779/application.log.txt)

似乎没有问题。

然后发现yao运行的console窗口有很多错误，并且最终导致yao直接退出：
[yao.console.log.txt](https://github.com/YaoApp/yao-knowledge/files/11678785/yao.console.log.txt)

服务器环境：
![image](https://github.com/YaoApp/yao-knowledge/assets/75373309/a47916ce-59c2-4414-8be1-a748e8b92499)

pdf.so是git后最近3天编译的linux版本的

**Comment by trheyi** [comment]
![image](https://github.com/YaoApp/yao-knowledge/assets/1842210/20e280fe-3c75-4d6f-ba91-6ec2919a5ba2)
